before:
  hooks:
    - make ui-dist
builds:
  - main: ./cmd/conduit/main.go
    id: conduit
    binary: conduit
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    tags:
      - ui
  # The S3 plugin
  - main: pkg/plugins/s3/cmd/s3/main.go
    id: s3
    binary: pkg/plugins/s3/s3
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  # The Postgres plugin
  - main: pkg/plugins/pg/cmd/pg/main.go
    id: pg
    binary: pkg/plugins/pg/pg
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  # The file plugin
  - main: pkg/plugins/file/cmd/file/main.go
    id: file
    binary: pkg/plugins/file/file
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  # The generator plugin
  - main: pkg/plugins/generator/cmd/generator/main.go
    id: generator
    binary: pkg/plugins/generator/generator
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  # The Kafka plugin
  - main: pkg/plugins/kafka/cmd/kafka/main.go
    id: kafka
    binary: pkg/plugins/kafka/kafka
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
archives:
  - builds:
      - conduit
      - s3
      - pg
      - file
      - generator
      - kafka
    allow_different_binary_count: true
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums_darwin.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  skip: true
